name: Generate Manifest

on:
  push:
    paths:
      - 'mods/**'
    branches:
      - main

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate manifest
        run: |
          python manifest_generator.py --base-url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/mods/"
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifest.json
          git commit -m "Update manifest.json" || echo "No changes to commit"
          git push